image:
- Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true
  
skip_commits:
  files:
    - '*.md'
    
install:
  - cinst gitversion.portable --version=3.6.4 -y
  - cinst gitlink --version=2.4.0 -y

configuration: Release

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - nuget restore .\Source\HelixToolkit.AppVeyor.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo
  
build_script:
  - msbuild Source/HelixToolkit.AppVeyor.sln "/property:Platform=Any CPU" "/property:Version=%GitVersion_NuGetVersion%" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - gitlink %APPVEYOR_BUILD_FOLDER% -u https://github.com/%APPVEYOR_REPO_NAME% -b master -f Source/HelixToolkit.AppVeyor.sln
  - nuget pack Source\HelixToolkit\HelixToolkit.nuspec -version "%GitVersion_NuGetVersion%"
  - nuget pack Source\HelixToolkit.Wpf\HelixToolkit.Wpf.nuspec -version "%GitVersion_NuGetVersion%"
  - nuget pack Source\HelixToolkit.Wpf.SharpDX\HelixToolkit.Wpf.Sharpdx.nuspec -version "%GitVersion_NuGetVersion%"
  - nuget pack Source\HelixToolkit.UWP\HelixToolkit.UWP.nuspec -version "%GitVersion_NuGetVersion%"
  - if "%APPVEYOR_REPO_NAME%" == "helix-toolkit/helix-toolkit" Source\build-dist-examples.cmd

artifacts:
  - path: '*.nupkg'
    name: HelixToolkit-packages-$(GitVersion_SemVer)
    type: zip
  - path: Source\dist-examples
    name: HelixToolkit-Examples-$(GitVersion_SemVer)
    type: zip
    
deploy:
  provider: NuGet
  server: https://www.myget.org/F/helix-toolkit/api/v2/package
  api_key:
    secure: 2GnqgfpkOUH6Umfn1WWlun0b021+QeInBXkgQOQfa4/wDOYHLT757rrjTsb0lmon
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
  on:
    APPVEYOR_REPO_NAME: helix-toolkit/helix-toolkit
