pull_requests:
  do_not_increment_build_number: true

install:
  - cinst gitversion.portable --version=3.4.1 -y
  - cinst gitlink --version=2.2.0 -y

configuration: Release

build:
  project: Source/HelixToolkit.AppVeyor.sln
  verbosity: normal

before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - nuget restore .\Source\HelixToolkit.AppVeyor.sln
  - gitversion /l console /output buildserver /updateAssemblyInfo

after_build:
  - gitlink c:\projects\helix-toolkit -u https://github.com/helix-toolkit/helix-toolkit -b master -f Source/HelixToolkit.AppVeyor.sln
  - nuget pack Source\HelixToolkit\HelixToolkit.nuspec -version "%GitVersion_NuGetVersion%"
  - nuget pack Source\HelixToolkit.Wpf\HelixToolkit.Wpf.nuspec -version "%GitVersion_NuGetVersion%"
  - nuget pack Source\HelixToolkit.Wpf.SharpDX\HelixToolkit.Wpf.Sharpdx.nuspec -version "%GitVersion_NuGetVersion%"

artifacts:
  - path: '*.nupkg'
    name: HelixToolkit-packages-$(GitVersion_SemVer)
    type: zip
    
deploy:
  provider: NuGet
  server: https://www.myget.org/F/helix-toolkit/api/v2/package
  api_key:
    secure: 2GnqgfpkOUH6Umfn1WWlun0b021+QeInBXkgQOQfa4/wDOYHLT757rrjTsb0lmon
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/
