version: 2015.1.{build}

environment:
  nuget_api_key:
    secure: kM3Kse+ivuuE5RVoe6dPdw+aguWx56K2YeXujGa9tMPQTms3lv7QxNpTLFMALYNa
      
install:
  - cinst stylecop -y
  - cinst LynxToolkit -y
  - cinst gitlink -Pre -y

platform: Any CPU

configuration: Release

build:
  project: Source/HelixToolkit.AppVeyor.sln
  verbosity: normal

before_build:
  - cmd: UpdateVersionNumbers /Version=%APPVEYOR_BUILD_VERSION% /ExtractReleaseNotes=CHANGELOG.md /Directory=Source

after_build:
  - cmd: gitlink c:\projects\helix-toolkit -u https://github.com/helix-toolkit/helix-toolkit -b master -f Source/HelixToolkit.AppVeyor.sln

deploy_script:
  - cmd: mkdir Packages
  - cmd: NuGet.exe pack Source\HelixToolkit\HelixToolkit.nuspec -OutputDirectory Packages
  - cmd: NuGet.exe pack Source\HelixToolkit.Wpf\HelixToolkit.Wpf.nuspec -OutputDirectory Packages
  - cmd: NuGet.exe pack Source\HelixToolkit.Wpf.SharpDX\HelixToolkit.Wpf.Sharpdx.nuspec -OutputDirectory Packages
  - cmd: for %%G in (Packages\*.nupkg) do NuGet.exe push %%G %nuget_api_key%
artifacts:
  - path: Output
    name: HelixToolkit-$(APPVEYOR_BUILD_VERSION)
    type: zip
  - path: Packages\*.nupkg
